:sparkles: Add translation for write_own_pipeline.mdx
Pseudo-Lab/diffusers pull request #13
Opened 2023-06-18 13:02 UTC by cuchoco

2023-06-19 01:47 UTC, cuchoco commented
timstep: `timestep` array 가 계속 등장해서 타임스텝 한국어 대신 timstep으로 표기했습니다.
noise residual, noisy residual: 노이즈 잔여량이라고 번역되었는데 일단은 영어 원문 그대로 표기했습니다.
diffusion: 디퓨전이라고 한국어로 적는게 더 나을까요?

2023-06-19 11:31 UTC, Snailpong requested changes

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +🧨 Diffusers는 사용자 친화적이며 유연한 도구 상자로, 사용사례에 맞게 diffusion 시스템을 구축 할 수 있도록 설계되었습니다. 이 도구 상자의 핵심은 모델과 스케줄러입니다.  [`DiffusionPipeline`]은 평의를 위해 이러한 구성 요소를 번들로 제공하지만, 파이프라인을 분리하고 모델과 스케줄러를 개별적으로 사용해 새로운 diffu
평의 -> 편의

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +2. 노이즈 제거 프로세스를 실행할 timestep수를 설정합니다:
timestep 수 띄어쓰기

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +다음 섹션에서는 여러분의 기술을 시험해보고 좀 더 복잡한 Stable Diffusion 파이프라인을 분석해 보겠습니다. 방법은 거의 동일합니다. 필요한 구성요소들을 초기화하고 timestep수를 설정하여 `timestep`배열을 생성합니다. 노이즈 제거 루프에서 `timestep`배열이 사용되며, 이 배열의 각 요소에 대해 모델은 노이즈가 적은 이미지를
nosie -> noisy

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +Stable Diffusion 은 텍스트-이미지 *latent diffusion* 모델입니다. latent diffusion 모델이라고 불리는 이유는 실제 픽셀 공간 대신 이미지의 저차원의 표현으로 작업하기 때문이고, 메모리 효율이 더 높습니다. 인코더는 이미지를 더 작은 표현으로 압축하고, 디코더는 압축된 표현을 다시 이미지로 변환합니다. 텍스트-이미지
텍스트-이미지 -> 영어로
필요하다는 것은

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +>>> prompt = ["a photograph of an astronaut riding a horse"]
주석도 가능하면 번역합니다!

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +또한 패딩 토큰의 임베딩인 *비조건부 텍스트 임베딩*을 생성해야 합니다. 이 임베딩은 조건부 `text_embeddings`과 동일한 모양(`batch_size` 그리고 `seq_length`)을 가져야 합니다:
unconditional

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +또한 패딩 토큰의 임베딩인 *비조건부 텍스트 임베딩*을 생성해야 합니다. 이 임베딩은 조건부 `text_embeddings`과 동일한 모양(`batch_size` 그리고 `seq_length`)을 가져야 합니다:
shape

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +두번의 포워드 패스를 피하기 위해 조건부 임베딩과 비조건부 임베딩을 배치로 연결하겠습니다:
forward pass

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +두번의 포워드 패스를 피하기 위해 조건부 임베딩과 비조건부 임베딩을 배치로 연결하겠습니다:
배치(batch)

2023-06-19 11:31 UTC, Snailpong commented on docs/source/ko/using-diffusers/write_own_pipeline.mdx
> +이것이 바로 🧨 Diffusers가 설계된 목적입니다: 모델과 스케줄러를 사용해 자신만의 디퓨전 시스템을 직관적이고 쉽게 작성할 수 있도록 하기 위해서입니다.
디퓨전 -> diffusion

2023-06-26 11:22 UTC, Snailpong approved these changes

2023-06-26 11:22 UTC, merged