unconditional_image_generation first draft
Pseudo-Lab/diffusers pull request #15
Opened 2023-06-19 10:42 UTC by mybloodykeyboard

2023-06-19 11:44 UTC, Snailpong requested changes

2023-06-19 11:44 UTC, tjdtnsu commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +무조건적 이미지 생성은 비교적 간단한 작업입니다. 모델이 텍스트나 이미지와 같은 추가 조건 없이 이미 학습된 훈련 데이터와 유사한 이미지만 생성합니다.
훈련 -> 학습

2023-06-19 11:44 UTC, tjdtnsu commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +[디퓨전 파이프라인]은 추론을 위해 미리 훈련된 디퓨전 시스템을 사용하는 가장 쉬운 방법입니다.
디퓨전 -> diffusion

2023-06-19 11:44 UTC, Snailpong commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +>>> from diffusers import DiffusionPipeline
` `` python 적어주세요

2023-06-19 11:44 UTC, Snailpong commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +출력은 기본적으로 PIL.Image 객체로 감싸집니다.
링크 원래대로 해주세요

2023-06-19 11:44 UTC, tjdtnsu commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +호출하여 이미지를 저장할 수 있습니다:
다음을 호출하여..

2023-06-19 11:45 UTC, mybloodykeyboard commented on docs/source/ko/using-diffusers/unconditional_image_generation.mdx
> +출력은 기본적으로 PIL.Image 객체로 감싸집니다.
PIL 링크

2023-07-06 12:27 UTC, Snailpong approved these changes

2023-07-06 12:27 UTC, merged