translate training/instructpix2pix
Pseudo-Lab/diffusers pull request #26
Opened 2023-07-16 02:37 UTC by jjuun0

2023-07-21 12:55 UTC, tjdtnsu requested changes
docs/source/ko/training/instructpix2pix.mdx에 있어야 합니다.
옮겨서 git commit --amend로 커밋 수정해주세요.

2023-07-22 13:47 UTC, jjuun0 commented
@Snailpong 수정했는데 혹시 잘 되었을까요?

2023-07-22 13:50 UTC, Snailpong commented
> @Snailpong 수정했는데 혹시 잘 되었을까요?

넹

2023-07-22 13:50 UTC, Snailpong approved these changes

2023-07-22 13:50 UTC, merged